test: &default

  # Credentials for REST APIs
  client_id: Aefc7tVb69fkHNpPXUlt-LqZ34vjMubs3voNVqH4HPMNU0fPefDYTMzRnAcGdmA3VpoTfdipGNPqsfou
  client_secret: ELkA2AuHNfm-t2A2MraDVzpcvG0eVPc_Hwv5J-P72tCKTEpvtXE9QuTMTe6F3W_edy580kbFD7uQTu6l

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  #app_id: APP-80W284485P519543T
  #username: jb-us-seller_api1.paypal.com
  #password: WX4WTU3S8MY44S7F
  #signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
